name: Build docker images

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  detect:
    name: Detect Changed Services
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Determine Changed Services
        id: get-matrix
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
           echo "Detecting changes..."
           CHANGED_FOLDERS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} apps | awk -F/ '!($2 ~ /^(Dockerfile|Makefile)$/) {print $2}' | sort -u | xargs)
           echo "Changed folders: $CHANGED_FOLDERS"


           matrix="{\"include\": ["
           first=1
           for service in $CHANGED_FOLDERS; do
             if [ -f "apps/${service}/Dockerfile" ]; then
               if [ $first -eq 0 ]; then
                 matrix+=","
               fi
               version=$(grep -o '"version": *"[^"]*"' apps/${service}/package.json | cut -d'"' -f4)
               matrix+="{\"service\": \"${service}\", \"version\": \"${version}\"}"
               first=0
             fi
           done
           matrix+="]}"
           
           echo "Matrix for build job: $matrix"
           echo "matrix=$matrix" >> $GITHUB_OUTPUT

      - name: Validate Matrix
        if: ${{ fromJson(steps.get-matrix.outputs.matrix).include[0] == null }}
        run: |
          echo "Output from previous step:"
          echo "${{ fromJson(steps.get-matrix.outputs.matrix).include.length }}"
          echo "${{ steps.get-matrix.outputs.matrix }}"
          echo "No services with a Dockerfile were changed. Exiting gracefully."
          exit 0
