name: Build docker images

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Detect Changed Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tags
        id: get-tags
        run: |
          package=$(echo ${{ github.ref_name }} | awk -F'@' '{print $1}')
          version=$(echo ${{ github.ref_name }} | awk -F'@' '{print $2}')
          echo Package: "$package"
          echo Version: "$version"
          echo "package=$package" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

          if [[ "$package" = '' ]] || [[ "$version" = '' ]]; then
            echo "This workflow was triggered without a package reference (git.ref_name). Please make sure it is triggered by a pac"
            exit 0
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ steps.get-tags.outputs.package }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.sha }}
            type=raw,value=release
            type=raw,value=v${{ steps.get-tags.outputs.version }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          file: apps/${{ steps.get-tags.outputs.package }}/Dockerfile
          platforms: linux/amd64
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
